name: Run Tests

run-name: Running all spec files to ensure they run clear before pull

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  check-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installing packages
        run: npm install

      - name: Running Tests
        run: npm run cy:headless
